FROM node:14.0.0-alpine

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && apk del .gyp

RUN mkdir -p /opt/frontend
WORKDIR /opt/frontend

# Install dependencies
COPY ./frontend/package.json .
COPY ./frontend/yarn.lock .
RUN yarn install --network-timeout 1000000
# RUN yarn upgrade

# Add rest of the client code
COPY ./frontend .
COPY ./entrypoint_dev.sh .

RUN chmod u+x entrypoint_dev.sh

EXPOSE 3000

# start server
ENTRYPOINT ["./entrypoint_dev.sh"]
