FROM node:14.0.0-alpine

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && apk del .gyp

RUN mkdir -p /opt/frontend
WORKDIR /opt/frontend

# Install dependencies
COPY ./frontend/package.json /opt/frontend
COPY ./frontend/yarn.lock /opt/frontend
RUN yarn install
# RUN yarn upgrade

# Add rest of the client code
COPY ./frontend/ /opt/frontend/
COPY ./entrypoint_dev.sh /opt/frontend/

RUN chmod u+x entrypoint_dev.sh

EXPOSE 3000

# start server
ENTRYPOINT ["./entrypoint_dev.sh"]
